version: '3.8'
services:
  php-evn:
    container_name: bkfood-php-server
    build: .
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80

  composer:
    restart: "no"
    image: composer:latest
    working_dir: /var/www/html
    command: update
    volumes:
      - ./src:/var/www/html/

  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1